version: '2'
services:
    jhipstersampleapplication-sonar:
        container_name: jhipstersampleapplication-sonar
        image: sonarqube:5.6-alpine
        ports:
            - 9000:9000
            - 9092:9092
